### ISSUE TITLE
Running a single test (ex. from within your ide) fails

### ISSUE THREAD

**Issue by midorlo** [Ardesco/Selenium-Maven-Template#52]
`mvn -Dtest=packahes.tests.GoogleExampleIT  ...`

    The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
```
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:124)
	at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:42)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:143)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:335)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:168)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at de.fubar.testing.framework.config.DriverType$1.getWebDriverObject(DriverType.java:63)
	at de.fubar.testing.framework.config.DriverFactory.instantiateWebDriver(DriverFactory.java:96)
	at de.fubar.testing.framework.config.DriverFactory.getDriver(DriverFactory.java:44)
	at de.fubar.testing.framework.DriverBase.getDriver(DriverBase.java:31)
	at de.fubar.testing.framework.tests.GoogleExampleIT.googleCheeseExample(GoogleExampleIT.java:20)

```

**Comment by Ardesco** [comment]
If you are running it inside your IDE you will need to specify the path to the driver binary, unless you invoke maven through your IDE.  The properties that set the path to the driver binaries are configured by a maven plugin.

**Comment by xmeng1** [comment]
maybe we can create a helper to set up the driver path in system property if detecting it runs under the IDE.  And add one option to signal it. Then add the option in the Run/Debug Configuration. Then all the run in the IDE will use the helper specified system property.

**Comment by Ardesco** [comment]
You don't need code for this really.  

- If you already have a driver binary installed and an env variable of webdriver.X.driver set up things will just work.
- If you want to specify a specific driver you can just set the property webdriver.chrome.driver to the location of a driver binary in the run/debug config for the individual test you are running

also above you are specifying a unit test name, not an integration test name, instead try:

```
mvn -Dit.test=GoogleExample verify
```
