### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Prudhveer-Reddy** [Ardesco/Selenium-Maven-Template#61]
whenever I run mvn commad,
I get the following
1556780876120	mozrunner::runner	INFO	Running command: "/usr/lib/firefox/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.XnsUOi4ypkj1"
*** You are running in headless mode.
1556780878108	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1556780878112	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1556780878112	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
JavaScript error: jar:file:///usr/lib/firefox/omni.ja!/components/nsPrompter.js, line 344: NS_ERROR_NOT_AVAILABLE: Cannot call openModalWindow on a hidden window
[Child 12107, Chrome_ChildThread] WARNING: pipe error (50): Connection reset by peer: file /build/firefox-6m4fHv/firefox-66.0.3+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 357
Exiting due to channel error.
Unable to capture screenshot...
org.openqa.selenium.WebDriverException: connection refused
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-31-17-90', ip: '172.31.17.90', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '1.8.0_211'
Driver info: driver.version: FirefoxDriver
remote stacktrace:

**Comment by Ardesco** [comment]
Please try and keep this to one issue, jumping around between various different issues doesn't help.

Problems I can see:

- The POM has been modified to use JDK 1.6, Selenium requires 1.8 as a minimum.
- Your POM looks like it has 2 versions of TestNG which is going to cause problems and you have a bunch of unused cucumber dependencies (unless they are used somewhere else)
- It looks like you are suffering from this Firefox error: https://github.com/SeleniumHQ/docker-selenium/issues/388
Do you get the same error if you try and run your tests through chrome?

**Comment by Prudhveer-Reddy** [comment]
Sorry Sir,
The project wasnt working, hence I restarted from the begining.
This is a fresh project. I directly cloned the code from your GiT repository.Now its not even working in my local machine.
1) Now I am using your project pom.xml file only sir.
When I run mvn install -Dbrowser=chrome , i get the following error.


Starting ChromeDriver 2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5) on port 32422
Only local connections are allowed.
 
Local Operating System: LINUX
Local Architecture: amd64
Selected Browser: chrome
Connecting to Selenium Grid: false
 
Starting ChromeDriver 2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5) on port 3580
Only local connections are allowed.
Unable to capture screenshot...
org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-1035-aws x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-31-17-90', ip: '172.31.17.90', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '11.0.2'
Driver info: driver.version: ChromeDriver
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at com.lazerycode.selenium.config.DriverType$2.getWebDriverObject(DriverType.java:43)
	at com.lazerycode.selenium.config.DriverFactory.instantiateWebDriver(DriverFactory.java:104)
	at com.lazerycode.selenium.config.DriverFactory.getDriver(DriverFactory.java:46)
	at com.lazerycode.selenium.DriverBase.getDriver(DriverBase.java:31)
	at com.lazerycode.selenium.listeners.ScreenshotListener.onTestFailure(ScreenshotListener.java:51)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:636)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Unable to clear cookies, driver object is not viable...
[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 3.525 s <<< FAILURE! - in com.lazerycode.selenium.tests.GoogleExampleIT
[ERROR] googleCheeseExample(com.lazerycode.selenium.tests.GoogleExampleIT)  Time elapsed: 2.457 s  <<< FAILURE!
org.openqa.selenium.WebDriverException: 
unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-1035-aws x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 793 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-31-17-90', ip: '172.31.17.90', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '11.0.2'
Driver info: driver.version: ChromeDriver
	at com.lazerycode.selenium.tests.GoogleExampleIT.googleCheeseExample(GoogleExampleIT.java:21)

[ERROR] googleMilkExample(com.lazerycode.selenium.tests.GoogleExampleIT)  Time elapsed: 0.292 s  <<< FAILURE!
org.openqa.selenium.WebDriverException: 
unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-1035-aws x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 111 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-31-17-90', ip: '172.31.17.90', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '11.0.2'
Driver info: driver.version: ChromeDriver
	at com.lazerycode.selenium.tests.GoogleExampleIT.googleMilkExample(GoogleExampleIT.java:50)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   GoogleExampleIT.googleCheeseExample:21->DriverBase.getDriver:31 » WebDriver un...
[ERROR]   GoogleExampleIT.googleMilkExample:50->DriverBase.getDriver:31 » WebDriver unkn...
[INFO] 
[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.1:verify (default) @ maven-template ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.382 s
[INFO] Finished at: 2019-05-02T09:57:04Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.1:verify (default) on project maven-template: There are test failures.
[ERROR] 
[ERROR] Please refer to /root/Selenium-Maven-Template/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Ardesco** [comment]
You will need to log onto the box that you are running tests against and see if you can actually start chrome or Firefox.  I'm going to make a guess that you don't have an X Windows system (https://en.wikipedia.org/wiki/X_Window_System) installed so the browsers are unable to render.

**Comment by Prudhveer-Reddy** [comment]
1) I am new to this platform sir, can you please tell me how to check if Chrome or Firefox is starting.
2) I am using an AWS EC2 Linux machine, can you tell me from where should I install X Windows system

**Comment by Ardesco** [comment]
I really can't tell you how to check if the AMI you built works properly.  At a bare minimum you will need to install the following:

`yum install xorg-x11-server-Xvfb.x86_64`

**Comment by Prudhveer-Reddy** [comment]
xorg-x11-server-Xvfb.x86_64 : This cannot be installed in Linus AWS machines.
However I got a clue. My friend is also using a similar AWS machine. When he ran your code in his machine it was working.
The output was shown as 
1556792360801	mozrunner::runner	INFO	Running command: "/usr/lib/firefox/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.8eFkBV3sds4e"
*** You are running in headless mode.
1556792362029	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1556792362050	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1556792362053	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*

**1556792364393	Marionette	INFO	Listening on port 33361
1556792364453	Marionette	WARN	TLS certificate errors will be ignored for this session**

May 02, 2019 10:19:24 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Page title is: Google
Page title is: Milk - Google Search
1556792367995	Marionette	INFO	Stopped listening on port 33361
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.623 s - in com.lazerycode.selenium.tests.GoogleExampleIT
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 

But in my machine , the Highlighted code is not coming. Does this have to do anything with **Marionette**
1556792364393	Marionette	INFO	Listening on port 33361
1556792364453	Marionette	WARN	TLS certificate errors will be ignored for this session

**Comment by Ardesco** [comment]
It's nothing to do with Marionette, Marionette is the internal name for geckodriver.

From what I can tell it's to do with you not having an X Window System on your Linux instance. If you don't have an X Window system running you are not going to be able to run any browsers, if you can't run browsers you can't run Selenium tests.

The best thing you can do is have a look at the differences between your AWS machine and your friends AWS machine and make yours match theirs (Or just make a copy of theirs).

**Comment by Prudhveer-Reddy** [comment]
Sir,
I get to realise that the code works when running with root user, but dosent work when running with jenkins,
Thants the sole difference.
Can you tell me what to do

**Comment by Ardesco** [comment]
You'll need to work out what your user doesn't have permissions to run and amend the permissions accordingly (e.g. does your user have execute privs for Firefox and chrome).

I'm going to close this off as invalid because there is nothing here than can be fixed with code.
